version: '3.4'

services:
  java-junior:
    image: ${DOCKER_REGISTRY-}java-junior
    container_name: students.app
    build:
      context: .
      dockerfile: Dockerfile
  students-db:
    image: mysql:latest
    container_name: students-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=studentsDB
    volumes:
      - ./.containers/database:/var/lib/mysql
    ports:
      - 3306:3306